#!/usr/bin/env python3
"""
train_v3.py
════════════════════════════════════════════════════════════════
Train Physics-Informed ST-GNN v3 with real-world data sources.

v3 improvements over v2:
  - dim_air = 10  (+canyon H/W ratio as 10th feature)
  - Tree heights from Meta Canopy Height Map (rasterio)
  - Building footprints from OpenStreetMap (overpy)
  - Surface materials auto-classified from OSM landuse
  - Street canyon wind correction (Oke 1988)
  - Multi-month calibration (Jun–Sep) instead of July only

Data pipeline for v3:
  1. python 01_data_generation/scripts/02_geometry_sampler.py \\
         --use_osm --use_canopy --canopy_tif data/canopy/<tile>.tif
  2. python 01_data_generation/scripts/03_lbt_batch_runner_v2_fast.py
         (same runner, picks up OSM geometry from scenarios.pkl)
  3. python 01_data_generation/scripts/04_sensing_calibration.py \\
         --months 6,7,8,9
  4. python 01_data_generation/scripts/05_output_to_hdf5_v2.py \\
         --suffix v3  (produces ground_truth_v3.h5)
  5. python train_v3.py

Conda env:  PytorchGPU
Usage:
  python train_v3.py [--device cuda --epochs 300]
"""

from __future__ import annotations

import sys
import argparse
from pathlib import Path

# ── Path setup ──────────────────────────────────────────────────
root_dir = Path(__file__).parent
sys.path.insert(0, str(root_dir))
sys.path.insert(0, str(root_dir / "02_graph_construction"))
sys.path.insert(0, str(root_dir / "03_model"))
sys.path.insert(0, str(root_dir / "04_training"))

import torch
from train import main as train_main
from urbangraph import DIM_AIR_V3


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train v3 ST-GNN (OSM + Canopy + Street Canyon, dim_air=10)"
    )

    data_dir = root_dir / "01_data_generation" / "outputs" / "raw_simulations"

    # ── Data paths ───────────────────────────────────────────────
    parser.add_argument(
        "--h5",
        default=str(data_dir / "ground_truth_v3.h5"),
        help="v3 ground truth HDF5 (generated by 05_output_to_hdf5 --suffix v3)",
    )
    parser.add_argument(
        "--scenarios",
        default=str(data_dir / "scenarios.pkl"),
        help="Scenarios pickle (generated with --use_osm / --use_canopy flags)",
    )
    parser.add_argument(
        "--epw",
        default=str(data_dir / "epw_data.pkl"),
    )
    parser.add_argument(
        "--seasonal_params",
        default=str(data_dir / "calibrated_params_seasonal.json"),
        help="Multi-month calibration JSON (from 04_sensing_calibration --months)",
    )

    # ── Model config ─────────────────────────────────────────────
    parser.add_argument(
        "--config",
        default=str(root_dir / "00_config" / "urbangraph_params.yaml"),
    )
    parser.add_argument(
        "--out",
        default="checkpoints_v3",
        help="Output checkpoint directory",
    )
    parser.add_argument(
        "--dim_air",
        type=int,
        default=DIM_AIR_V3,   # 10
        help="Air node feature dimension (default=10 for v3)",
    )

    # ── Training hyperparameters ─────────────────────────────────
    parser.add_argument("--epochs",     type=int,   default=300)
    parser.add_argument("--batch_size", type=int,   default=1)
    parser.add_argument("--lr",         type=float, default=3e-4,
                        help="Learning rate (lower than v2 for fine-tuning)")
    parser.add_argument(
        "--device",
        default="cuda" if torch.cuda.is_available() else "cpu",
    )
    parser.add_argument(
        "--finetune_from",
        default="",
        help="Optional: path to v2 checkpoint to fine-tune from",
    )
    parser.add_argument(
        "--live-plot",
        dest="live_plot", action="store_true", default=True,
    )
    parser.add_argument(
        "--no-live-plot",
        dest="live_plot", action="store_false",
        help="Disable live plot (headless / SSH mode)",
    )

    args = parser.parse_args()

    # ── GPU info ─────────────────────────────────────────────────
    if args.device == "cuda":
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9
            print(f"  GPU: {gpu_name}  ({vram_gb:.1f} GB VRAM)")
        else:
            print("  WARNING: CUDA requested but not available → falling back to CPU")
            args.device = "cpu"

    # ── Banner ───────────────────────────────────────────────────
    print("\n" + "=" * 70)
    print("  ST-GNN v3 Training  |  PytorchGPU conda env")
    print("=" * 70)
    print(f"  dim_air      : {args.dim_air}  "
          f"(+canyon H/W vs v2's {args.dim_air - 1})")
    print(f"  Data         : {Path(args.h5).name}")
    print(f"  Checkpoints  : {args.out}/")
    print(f"  Device       : {args.device}")
    print(f"  Max epochs   : {args.epochs}")
    print(f"  LR           : {args.lr}")
    if args.finetune_from:
        print(f"  Fine-tune    : {args.finetune_from}")
    print("=" * 70)
    print()

    # ── Optional: validate data file exists ──────────────────────
    h5_path = Path(args.h5)
    if not h5_path.exists():
        print(f"  WARNING: HDF5 not found: {h5_path}")
        print("  Run the v3 data pipeline first:")
        print("    python 01_data_generation/scripts/02_geometry_sampler.py "
              "--use_osm --use_canopy")
        print("    python 01_data_generation/scripts/03_lbt_batch_runner_v2_fast.py")
        print("    python 01_data_generation/scripts/04_sensing_calibration.py "
              "--months 6,7,8,9")
        print("    python 01_data_generation/scripts/05_output_to_hdf5_v2.py "
              "--suffix v3")
        print()

    # ── Launch training ──────────────────────────────────────────
    train_main(
        cfg_path      = args.config,
        h5_path       = args.h5,
        scenario_pkl  = args.scenarios,
        epw_pkl       = args.epw,
        out_dir       = args.out,
        device_str    = args.device,
        live_plot     = args.live_plot,
        dim_air       = args.dim_air,
        finetune_ckpt = args.finetune_from or None,
        lr            = args.lr,
        max_epochs    = args.epochs,
    )


if __name__ == "__main__":
    main()
